services:
  SERVICE_NAME:
    build: .
    container_name: ${SITE_NAME}
    restart: always
    volumes:
      - ./app:/app/public
    environment:
      - "SERVER_ROOT=/app/public"
    ports:
      - "80:80"
      - "443:443"
    deploy:
      resources:
        limits:
          cpus: 'CPU_LIMIT'
          memory: MEMORY_LIMIT
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
