services:
  SERVICE_NAME:
    build: .
    container_name: ${SITE_NAME}
    restart: always
    volumes:
      - ./app:/app
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SITE_NAME}.rule=Host(`${SITE_URL}`)"
      - "traefik.http.routers.${SITE_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${SITE_NAME}.tls.certresolver=le"
      - "traefik.http.services.${SITE_NAME}.loadbalancer.server.port=3000"
    networks:
      - web
    deploy:
      resources:
        limits:
          cpus: 'CPU_LIMIT'
          memory: MEMORY_LIMIT
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"

networks:
  web:
    external: true
